# yaml 配置实例
version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.6.2
    ports:
      - "9100:9100"
      - "9200:9200"
    networks:
      - somenetwork
    environment:
      - discovery.type=single-node
  kibana:
    image: kibana:7.6.2
    ports:
      - "5601:5601"
    networks:
      - somenetwork
networks:
  somenetwork:
    driver: bridge
