# yaml 配置实例
version: '3'
services:
  zookeeper_2:
   build:
    context: .
    dockerfile: Dockerfile
   container_name: zookeeper_2
   ports:
    - "2181:2181"
   networks:
    zookeeper_network:
     ipv4_address: 199.18.0.2
   environment:
    HOSTNAME: zookeeper_2
    DATANODE: 2
  zookeeper_3:
   build:
    context: .
    dockerfile: Dockerfile
   container_name: zookeeper_3
   networks:
    zookeeper_network:
     ipv4_address: 199.18.0.3
   environment:
    HOSTNAME: zookeeper_3
    DATANODE: 3
  zookeeper_4:
   build:
    context: .
    dockerfile: Dockerfile
   container_name: zookeeper_4
   networks:
    zookeeper_network:
     ipv4_address: 199.18.0.4
   environment:
    HOSTNAME: zookeeper_4
    DATANODE: 4
networks:
 zookeeper_network:
  ipam:
   config:
    - subnet: 199.18.0.0/16
